depth: 9
crop: 0.20
smooth: 6
adaptive: true
adapt_iters: 12
adapt_low_q: 0.10
adapt_high_q: 0.90
adapt_gamma: 2.0
cloud_cleanup:
  height_q: 0.85
  low_density_q: 0.35
colorize: true
color_k: 3
decimate_target: 150000
method: poisson
save_obj: true
