depth: 10
crop: 0.15
smooth: 4
adaptive: true
adapt_iters: 12
adapt_low_q: 0.10
adapt_high_q: 0.90
adapt_gamma: 1.6
cloud_cleanup:
  height_q: 0.90
  low_density_q: 0.25
colorize: true
color_k: 4
decimate_target: 250000
method: poisson
save_obj: true
