depth: 8
crop: 0.25
smooth: 2
adaptive: true
adapt_iters: 8
adapt_low_q: 0.20
adapt_high_q: 0.80
adapt_gamma: 1.2
cloud_cleanup:
  height_q: 0.92
  low_density_q: 0.25
colorize: true
color_k: 3
decimate_target: 120000
method: poisson
save_obj: true
