depth: 11
crop: 0.08
smooth: 1
adaptive: true
adapt_iters: 10
adapt_low_q: 0.05
adapt_high_q: 0.95
adapt_gamma: 1.0
cloud_cleanup:
  height_q: 0.93
  low_density_q: 0.25
colorize: true
color_k: 5
decimate_target: 0
method: bpa
save_obj: true
